version: '3.7'

networks:
  project:
    driver: bridge 

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: front-dt1
    volumes:
      - .:/usr/front-dt1/app
    ports:
      - 8080:8080
    restart: always
    tty: true
    networks:
      - project